### ISSUE TITLE
Future Plans, Todo & Contributing

### ISSUE THREAD

**Issue by OfficialCRUGG** [taigahq/lanyard.js#4]
**Todo**
- [x] Basic Interaction with the REST API (1.0.0 & 1.4.0)
- [ ] Class based syntax (1.5.0) => #2 
- [ ] Go dependency free (1.6.0)
- [ ] Support getting data about multiple users at once (1.7.0)
- [ ] WebSocket support (1.8.0)

**Contributing**
When a previous version releases, a Draft PR for the next release gets created. (Current one is #2)
In that, a list of features for the update can be found. In brackets, you can always find who is assigned to this feature. If you wish to contribute a specific feature, reply to the PR that you wish to be assigned to that. Once the original message has been updated to have you in the brackets, you can add the feature in a fork and then create a PR to the `development` branch.
